# docker-compose.yml
version: '3.0'
services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: password
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PG_PASSWORD: password
